/*

	编辑器 配置 文件
	------
	-------->文件虽为js类型但不建议在这里写与配置不相干代码<-------------
	=----=
	---为什么配置文件选择js格式？---因为方便在本地调用，不会出现跨域问题

*/
var config={
	//菜单栏工具
	tools:[
		{
			title:'打开图片',//标题
			icon:'asset/imgs/folder.png',//图标
			action:'openfile()'//事件
		},
		{
			title:'保存图片',//标题
			icon:'asset/imgs/save.png',//图标
			action:'svaeimg()'//事件
		},
		{
			title:'取消选择',//标题
			icon:'asset/imgs/Pointer.png',//图标
			action:'cancel()'//事件
		},
		{
			title:'多边形选择',//标题
			icon:'asset/imgs/polygon.svg',//图标
			action:'startpolygon(this)'//事件
		},
		{
			title:'删除选择',//标题
			icon:'asset/imgs/emptytrash.png',//图标
			action:'del_select()'//事件
		},
		{
			title:'色彩平衡',//标题
			icon:'asset/imgs/Color.png',//图标
			action:'opencolorwindow(this)'//事件
		},
		{
			title:'裁剪',//标题
			icon:'asset/imgs/cut.svg',//图标
			action:'startcut(this)'//事件
		},
		{
			title:'移动画布',//标题
			icon:'asset/imgs/move.svg',//图标
			action:'movecanvas(this)'//事件
		},
		{
			title:'重置画布',//标题
			icon:'asset/imgs/Restore.png',//图标
			action:'resetcavans()'//事件
		},
		{
			title:'画笔',//标题
			icon:'asset/imgs/paintbrush.svg',//图标
			action:'startdraw(this)'//事件
		},
		{
			title:'拾色器',//标题
			icon:'asset/imgs/colorpicker.png',//图标
			action:'pickercolor(this)'//事件
		},
		{
			title:'铅笔',//标题
			icon:'asset/imgs/pencil.svg',//图标
			action:'startpencil(this)'//事件
		},
		{
			title:'填充',//标题
			icon:'asset/imgs/fill.png',//图标
			action:'fillcolor()'//事件
		},
		{
			title:'擦除',//标题
			icon:'asset/imgs/eraser.svg',//图标
			action:'startclaer(this)'//事件
		},
		{
			title:'画笔抠图',//标题
			icon:'asset/imgs/pen.svg',//图标
			action:'pencut(this)'//事件
		},
		{
			title:'帮助',//标题
			icon:'asset/imgs/help.png',//图标
			action:'helper()'//事件
		},
	],
	tools_control:[
		{
			title:'容差',
			edit_type:'input',
			value:'0',
			event:'settolerance(this)',
			click:''
		},
		{
			title:'笔刷大小',
			edit_type:'input',
			value:'10',
			event:'setpensize(this)',
			click:''
		},
		{
			title:'笔刷颜色',
			edit_type:'color',
			value:'',
			event:'changecolor(this)',
			click:'selectcolor(this)'
		},
		{
			title:'显示比例',
			edit_type:'input',
			value:'100',
			event:'scalecavans(this)',
			click:''
		},
	]
}